# Generated by Django 4.1.3 on 2022-12-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
