# Generated by Django 4.1.3 on 2022-12-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_employee_address_alter_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='picture1.png', null=True, upload_to=''),
        ),
    ]
