# Generated by Django 4.1.3 on 2023-01-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
