# Generated by Django 4.1.3 on 2023-01-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='LifeSpan',
            field=models.CharField(blank=True, default='10Yrs', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='Warantee_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='Warantee_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='City',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Company_Name',
            field=models.CharField(max_length=50),
        ),
    ]
